# Generated by Django 4.0.4 on 2022-06-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='albums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main.album', verbose_name='Albums'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='songs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main.song', verbose_name='Songs'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subscription', verbose_name='Subscriptions'),
        ),
    ]
