# Generated by Django 4.0.4 on 2022-06-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_song_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
