<<<<<<< HEAD
version: '3.9'
services:

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8090:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - song_app
    networks:
      - main_app_network

  database:
    image: postgres:latest
    container_name: main_app_postgresql_container
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill
    ports:
      - 5436:5436
    command:
      - -p 5436
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "main_db"]
      retries: 5
      timeout: 10s
      interval: 10s
    networks:
      - main_app_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      retries: 5
      interval: 10s
      timeout: 10s
    networks:
      - main_app_network

  song_app:
    build: .
    container_name: project_container
    restart: unless-stopped
    ports:
      - 8000:8000
    healthcheck:
      timeout: 10s
      retries: 5
      interval: 10s
      test: ["CMD", "curl", "http://localhost:8000/healthcheck/"]
    env_file:
      - ./env_file.env
    depends_on:
      - database
      - redis
    networks:
      - main_app_network

networks:
  main_app_network:
    external: true
    name: global_project_network



