version: '3.9'

services:

  nginx_container:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 8090:80
    command:
      - rm /etc/nginx/sites-enabled/default
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - main_app
    networks:
      - main_app_network

  rabbitmq_message_database:
    container_name: rabbitmq_message_database
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5430:5430
    healthcheck:
      test: ["CMD", "curl", "-f", "postgresql://"]
      interval: 15s
      retries: 5
    networks:
      - main_app_network

  rabbitmq_server:
    container_name: rabbitmq_server
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    volumes:
      - ./rabbitmq-entrypoint.sh:/init.sh
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - 15672:15672
      - 5671:5672
    networks:
      - main_app_network
    depends_on:
      - rabbitmq_message_database

  database:
    build: ./postgres/.
    container_name: main_app_postgresql_container
    environment:
      POSTGRES_DB: main_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kirill
    ports:
      - 5436:5436
    command:
      - -p 5436
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "main_db"]
      retries: 5
      timeout: 10s
      interval: 10s
    networks:
      - main_app_network

  redis:
    image: redis:latest
    container_name: redis_container
    command:
      - redis-server --requirepass REDIS_PASSWORD=REDIS_PASSWORD
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      retries: 5
      interval: 10s
      timeout: 10s
    networks:
      - main_app_network

  song_app:
    build: .
    container_name: project_container
    restart: unless-stopped
    ports:
      - 8000:8000
    healthcheck:
      timeout: 10s
      retries: 5
      interval: 10s
      test: ["CMD", "curl", "http://localhost:8000/healthcheck/"]
    env_file:
      - ./env_file.env
    depends_on:
      - database
      - redis
      - chat_web_service
      - rabbitmq_server
    networks:
      - main_app_network

networks:
  main_app_network:
    external: true
    name: global_application_network

