version: "3.9"
services:

  mongo_db:
    image: mongo:latest
    container_name: mongo_database
    environment:
      - MONGO_INITDB_DATABASE=mongo_sub_db
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password
    ports:
      - 27016:27016
      - 27018:27018

    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./data:/data/db
    command: mongod --port 27018

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 127.0.0.1:27018/mongo_db --quiet
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped
