version: "3.9"
services:
  rabbitmq_broker_celery_server:

      container_name: rabbitmq_celery_broker_server
      image: rabbitmq:3-management
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

      environment:
        - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
      ports:
        - 5675:5672
        - 15673:15673
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5675/api/healthchecks/node"]
        retries: 5
        timeout: 10s
        interval: 20s
