# Generated by Django 3.2.13 on 2022-05-24 05:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APICustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('balance', models.IntegerField(default=0, verbose_name='User Balance')),
                ('created_at', models.DateField(default=datetime.datetime(2022, 5, 24, 5, 39, 31, 677844, tzinfo=utc), verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'API Sub Customer',
                'verbose_name_plural': 'API Sub Customers',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_name', models.CharField(max_length=100, verbose_name='Name')),
                ('owner_id', models.IntegerField(verbose_name='Owner Id')),
                ('amount', models.IntegerField(max_length=100, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eu', 'eu'), ('rub', 'rub')], default='usd', max_length=20, verbose_name='Currency')),
                ('created_at', models.DateField(auto_now_add=True, max_length=100, null=True, verbose_name='Expire Period')),
                ('purchasers', models.ManyToManyField(related_name='purchased_subs', to='main.APICustomer', verbose_name='Purchasers')),
            ],
        ),
    ]
