# Generated by Django 3.2.13 on 2022-05-24 07:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicustomer',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 5, 24, 7, 18, 43, 584090, tzinfo=utc), verbose_name='Created At'),
        ),
    ]
