# Generated by Django 4.0.4 on 2022-05-17 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_outcast', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': 'Group Chat', 'verbose_name_plural': 'Group Chats'},
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='admins',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='logo',
            field=models.CharField(default='/Users/kirillklimushin/Desktop/VideoHost/VideoHost/main/static/images//default.png', max_length=300, null=True, verbose_name='Group Avatar Link'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_image',
            field=models.URLField(max_length=100, null=True, verbose_name='User Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='is_blocked'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='chat_groups', to=settings.AUTH_USER_MODEL, verbose_name='Group Members'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Is Authenticated'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=main.models.PhoneNumberField(max_length=100, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=100, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_link',
            field=models.CharField(max_length=100, verbose_name='File AWS Key Link'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='created_at_index'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.chatgroup'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
